# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_list', '0002_auto_20161127_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_url',
            field=models.CharField(default='/', max_length=200),
            preserve_default=False,
        ),
    ]
