# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monosaur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.FloatField(blank=True, null=True)),
                ('subscription_url', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monosaur.Company')),
            ],
        ),
    ]
