# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0002_auto_20161128_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
