# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription',
            field=models.CharField(max_length=100),
        ),
    ]
