# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spend_analyser.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='classification',
            new_name='category',
        ),
    ]
