# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0004_auto_20161203_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
