# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0005_transaction_is_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_subscription',
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.CharField(default='No', max_length=100),
            preserve_default=False,
        ),
    ]
