# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0006_auto_20161203_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
