# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0006_auto_20161203_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spend_analyser.Category'),
        ),
    ]
