# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0007_auto_20161207_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_list.Subscription'),
        ),
    ]
