# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_analyser', '0009_auto_20161207_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
